### ISSUE TITLE
default branch to repository’s default_branch

### ISSUE THREAD

**Issue by gr2m** [RichardLitt/add-file-to-github-repo#5]
it is currently hardcoded to default to master

**Comment by RichardLitt** [comment]
Shouldn't be? https://github.com/RichardLitt/add-file-to-github-repo/blob/f2aa71f667b885b088e57a2323aaf2cb142e77b8/index.js#L32

**Comment by RichardLitt** [comment]
Ah, I see. Good idea.

**Comment by gr2m** [comment]
instead of `master`, fetch the repository and read out it’s default branch
